SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for DEPARTMENT
-- ----------------------------
DROP TABLE IF EXISTS `DEPARTMENT`;
CREATE TABLE `DEPARTMENT` (
  `DEPARTMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `FACILITY_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`),
  KEY `FK_qq3sdctrbi73eog27whses3bm` (`FACILITY_ID`),
  CONSTRAINT `FK_qq3sdctrbi73eog27whses3bm` FOREIGN KEY (`FACILITY_ID`) REFERENCES `FACILITY` (`FACILITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for DEVICE
-- ----------------------------
DROP TABLE IF EXISTS `DEVICE`;
CREATE TABLE `DEVICE` (
  `DEVICE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `DEVICE_USAGE` varchar(256) DEFAULT NULL,
  `MANUFACTURER` varchar(256) DEFAULT NULL,
  `MODEL` varchar(128) DEFAULT NULL,
  `SERIAL_NUMBER` varchar(128) DEFAULT NULL,
  `ROOM_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DEVICE_ID`),
  KEY `FK_n6bxmln20uuwq0xe520hvpn1a` (`ROOM_ID`),
  CONSTRAINT `FK_n6bxmln20uuwq0xe520hvpn1a` FOREIGN KEY (`ROOM_ID`) REFERENCES `ROOM` (`ROOM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for DEVICE_SESSION_TEMPLATE
-- ----------------------------
DROP TABLE IF EXISTS `DEVICE_SESSION_TEMPLATE`;
CREATE TABLE `DEVICE_SESSION_TEMPLATE` (
  `DEVICE_ID` bigint(20) NOT NULL,
  `SESSION_TEMPLATE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`DEVICE_ID`,`SESSION_TEMPLATE_ID`),
  KEY `FK_DEVICE_SESSION_TEMPLATE_SESSION_TEMPLATE` (`SESSION_TEMPLATE_ID`),
  KEY `FK_DEVICE_DEVICE_SESSION_TEMPLATE` (`DEVICE_ID`),
  CONSTRAINT `FK_DEVICE_DEVICE_SESSION_TEMPLATE` FOREIGN KEY (`DEVICE_ID`) REFERENCES `DEVICE` (`DEVICE_ID`),
  CONSTRAINT `FK_DEVICE_SESSION_TEMPLATE_SESSION_TEMPLATE` FOREIGN KEY (`SESSION_TEMPLATE_ID`) REFERENCES `SESSION_TEMPLATE` (`SESSION_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for FACILITY
-- ----------------------------
DROP TABLE IF EXISTS `FACILITY`;
CREATE TABLE `FACILITY` (
  `FACILITY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(256) DEFAULT NULL,
  `CITY` varchar(256) DEFAULT NULL,
  `CONTACT_PERSON` varchar(256) DEFAULT NULL,
  `EMAIL` varchar(256) DEFAULT NULL,
  `PHONE` varchar(32) DEFAULT NULL,
  `PIB` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`FACILITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for MEASURE
-- ----------------------------
DROP TABLE IF EXISTS `MEASURE`;
CREATE TABLE `MEASURE` (
  `MEASURE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(256) DEFAULT NULL,
  `UNIT` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`MEASURE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for MEASURED_VALUE
-- ----------------------------
DROP TABLE IF EXISTS `MEASURED_VALUE`;
CREATE TABLE `MEASURED_VALUE` (
  `MEASURED_VALUE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DOUBLE_VALUE` double DEFAULT NULL,
  `STRING_VALUE` varchar(64) DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `MEASURE_ID` bigint(20) DEFAULT NULL,
  `MEASUREMENT_ID` bigint(20) DEFAULT NULL,
  `IDX` int(11) DEFAULT NULL,
  PRIMARY KEY (`MEASURED_VALUE_ID`),
  KEY `FK_mrv86cfqei7676wk0w1qlmb4` (`MEASURE_ID`),
  KEY `FK_j26bos6lp7moxohdqjdqefn5c` (`MEASUREMENT_ID`),
  CONSTRAINT `FK_j26bos6lp7moxohdqjdqefn5c` FOREIGN KEY (`MEASUREMENT_ID`) REFERENCES `MEASUREMENT` (`MEASUREMENT_ID`),
  CONSTRAINT `FK_mrv86cfqei7676wk0w1qlmb4` FOREIGN KEY (`MEASURE_ID`) REFERENCES `MEASURE` (`MEASURE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=389 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for MEASUREMENT
-- ----------------------------
DROP TABLE IF EXISTS `MEASUREMENT`;
CREATE TABLE `MEASUREMENT` (
  `MEASUREMENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SESSION_TEMPLATE_ID` bigint(20) DEFAULT NULL,
  `IDX` int(11) DEFAULT NULL,
  `SESSION_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`MEASUREMENT_ID`),
  KEY `FK_263uel60heyf734kq4awp0sh9` (`SESSION_TEMPLATE_ID`),
  KEY `FK_btuqpr6b1r91rar8i6rd64dk4` (`SESSION_ID`),
  CONSTRAINT `FK_263uel60heyf734kq4awp0sh9` FOREIGN KEY (`SESSION_TEMPLATE_ID`) REFERENCES `SESSION_TEMPLATE` (`SESSION_TEMPLATE_ID`),
  CONSTRAINT `FK_btuqpr6b1r91rar8i6rd64dk4` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION` (`SESSION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for POLICY
-- ----------------------------
DROP TABLE IF EXISTS `POLICY`;
CREATE TABLE `POLICY` (
  `POLICY_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`POLICY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for ROLE
-- ----------------------------
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE` (
  `ROLE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for ROLE_POLICY
-- ----------------------------
DROP TABLE IF EXISTS `ROLE_POLICY`;
CREATE TABLE `ROLE_POLICY` (
  `ROLE_ID` bigint(20) NOT NULL,
  `POLICY_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`POLICY_ID`),
  KEY `FK465DCD1B4F35C257` (`POLICY_ID`) USING BTREE,
  KEY `FK465DCD1BE1C09F17` (`ROLE_ID`) USING BTREE,
  CONSTRAINT `FK_5u6cxr5ch9ya60hb39oeydfao` FOREIGN KEY (`POLICY_ID`) REFERENCES `POLICY` (`POLICY_ID`),
  CONSTRAINT `FK_8pnrkm82r5udhrnyxyuv8h8ew` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for ROOM
-- ----------------------------
DROP TABLE IF EXISTS `ROOM`;
CREATE TABLE `ROOM` (
  `ROOM_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `INSPECTION_INTERVAL` bigint(20) DEFAULT NULL,
  `DEPARTMENT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ROOM_ID`),
  KEY `FK_gasrk1edv44txxe1teeubx2cm` (`DEPARTMENT_ID`),
  CONSTRAINT `FK_gasrk1edv44txxe1teeubx2cm` FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENT` (`DEPARTMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for SESSION
-- ----------------------------
DROP TABLE IF EXISTS `SESSION`;
CREATE TABLE `SESSION` (
  `SESSION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `COMMENT` varchar(1024) DEFAULT NULL,
  `SESSION_PERFORM_DATE` datetime DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `DEVICE_ID` bigint(20) DEFAULT NULL,
  `SESSION_TEMPLATE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`SESSION_ID`),
  KEY `FK_137b94e7xy10tveynn2svv8ya` (`DEVICE_ID`),
  KEY `FK_dqs51r4ritcbd5iksd5q1sjpj` (`SESSION_TEMPLATE_ID`),
  CONSTRAINT `FK_137b94e7xy10tveynn2svv8ya` FOREIGN KEY (`DEVICE_ID`) REFERENCES `DEVICE` (`DEVICE_ID`),
  CONSTRAINT `FK_dqs51r4ritcbd5iksd5q1sjpj` FOREIGN KEY (`SESSION_TEMPLATE_ID`) REFERENCES `SESSION_TEMPLATE` (`SESSION_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for SESSION_TEMPLATE
-- ----------------------------
DROP TABLE IF EXISTS `SESSION_TEMPLATE`;
CREATE TABLE `SESSION_TEMPLATE` (
  `SESSION_TEMPLATE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(1024) DEFAULT NULL,
  `NAME` varchar(64) DEFAULT NULL,
  `TESTING_PARAMETER` int(11) DEFAULT NULL,
  `UPLOAD_REQUIRED` bit(1) DEFAULT NULL,
  `TESTING_MEASURE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`SESSION_TEMPLATE_ID`),
  KEY `FK_irhgpsnbkq5tlgnjvi6ag5akq` (`TESTING_MEASURE_ID`),
  CONSTRAINT `FK_irhgpsnbkq5tlgnjvi6ag5akq` FOREIGN KEY (`TESTING_MEASURE_ID`) REFERENCES `MEASURE` (`MEASURE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for SESSION_TEMPLATE_MEASURE
-- ----------------------------
DROP TABLE IF EXISTS `SESSION_TEMPLATE_MEASURE`;
CREATE TABLE `SESSION_TEMPLATE_MEASURE` (
  `SESSION_TEMPLATE_MEASURE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TYPE` int(11) DEFAULT NULL,
  `MEASURE_ID` bigint(20) DEFAULT NULL,
  `SESSION_TEMPLATE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`SESSION_TEMPLATE_MEASURE_ID`),
  KEY `FK_cfol7mlsuo13gd5op5v80ta25` (`MEASURE_ID`),
  KEY `FK_ssnqxkru5pox2crtsgu99d61j` (`SESSION_TEMPLATE_ID`),
  CONSTRAINT `FK_cfol7mlsuo13gd5op5v80ta25` FOREIGN KEY (`MEASURE_ID`) REFERENCES `MEASURE` (`MEASURE_ID`),
  CONSTRAINT `FK_ssnqxkru5pox2crtsgu99d61j` FOREIGN KEY (`SESSION_TEMPLATE_ID`) REFERENCES `SESSION_TEMPLATE` (`SESSION_TEMPLATE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for USER_PROFILE
-- ----------------------------
DROP TABLE IF EXISTS `USER_PROFILE`;
CREATE TABLE `USER_PROFILE` (
  `USER_PROFILE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(64) DEFAULT NULL,
  `LAST_NAME` varchar(64) DEFAULT NULL,
  `PASSWORD` varchar(64) DEFAULT NULL,
  `USERNAME` varchar(64) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`USER_PROFILE_ID`),
  KEY `FK_rdp5qad4a6nhxrg0ccux6tvs5` (`ROLE_ID`),
  CONSTRAINT `FK_rdp5qad4a6nhxrg0ccux6tvs5` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for USER_PROFILE_FACILITY
-- ----------------------------
DROP TABLE IF EXISTS `USER_PROFILE_FACILITY`;
CREATE TABLE `USER_PROFILE_FACILITY` (
  `USER_PROFILE_ID` bigint(20) NOT NULL,
  `FACILITY_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`USER_PROFILE_ID`,`FACILITY_ID`),
  KEY `FK5D56D28DF558A006` (`USER_PROFILE_ID`) USING BTREE,
  KEY `UK_3gncqjjmds4u47324yofvue72` (`FACILITY_ID`) USING BTREE,
  CONSTRAINT `FK_3gncqjjmds4u47324yofvue72` FOREIGN KEY (`FACILITY_ID`) REFERENCES `FACILITY` (`FACILITY_ID`),
  CONSTRAINT `FK_qvi0s2lwmi978s2aa0bqde25v` FOREIGN KEY (`USER_PROFILE_ID`) REFERENCES `USER_PROFILE` (`USER_PROFILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
